module.exports = {
    ADDED_SUCCESSFULLY: "Added successfully",
    USER_DATA_MISSING: "User not found.",
    DATA_SUBMITED_SUCCESSFULLY: "Data submited successfully",
    PROfILE_CREATED_SUCCESSFULLY: "Profile created successfully.",
    EMAIL_MISSING: "Email Id is missing.",
    PHONE_MISSING: "Phone number is missing.",
    DIAL_CODE_MISSING: "Dial code missing.",
    ACCOUNT_CREATED_SUCCESSFULLY: "Account created successfully.",
    EMAIL_ALREADY_IN_USE: "Email Id already in use.",
    EMAIL_NOT_VERIFIED: "Email Id is not verified.",
    UPLOAD_SUCCESS: "Uploaded successfully.",
    PHONE_ALREADY_IN_USE: "Phone number already in use.",
    INVALID_CREDENTIALS: "Invalid credentials.",
    INVALID_DATA: "Invalid data.",
    ACCOUNT_BLOCKED: "Your account has been blocked.",
    ACCOUNT_DELETED_SUCCESSFULLY: "Account deleted successfully.",
    LOGIN_SUCCESS: "Logged in successfully.",
    LOGOUT_SUCCESS: "Logged out successfully.",
    DATA_FETCHED: "Data fetched successfully.",
    EMAIL_ALREADY_EXISTS: "Email already in use.",
    PHONE_ALREADY_EXISTS: "Phone number already in use.",
    UPLOADING_ERROR: "Uploading error.",
    IMAGE_UPLOADED: "Image uploaded successfully.",
    ACCOUNT_DELETED: "Account deleted successfully.",
    NO_DATA_SUCCESS: "No data success.",
    OTP_SENT: "OTP sent successfully.",
    OTP_SENT_PHONE: "OTP sent successfully on phone.",
    OTP_SENT_EMAIL: "OTP sent successfully on email.",
    OTP_EXPIRED: "OTP expired.",
    INVALID_OTP: "Invalid OTP .",
    INVALID_INPUT: "Invalid input",
    ACCOUNT_VERIFIED: "Account verified successfully.",
    OTP_VERIFIED: "Otp verified successfully.",
    ACCOUNT_PHONE: "Phone number verified successfully.",
    PROFILE_UPDATED_SUCCESSFULLY: "Profile updated successfully.",
    PROFILE_DELETED_SUCCESSFULLY: "Profile deleted successfully.",
    ADMIN_NOT_FOUND: "Admin data not found.",
    ACCOUNT_NOT_FOUND: "Account doesn't exist.",
    PASSWORD_CHANGED_SUCCESSFULLY: "Password changed successfully.",
    PASSWORDS_SHOULD_BE_DIFFERENT: "New password should be different from the old password.",
    OLD_PASS_NOT_MATCH: "Old password is not correct",
    PASSWORD_NOT_SET: "Password not set",
    SUCCESS: "Success.",
    LINK_SENT: "Forgot password link sent successfully.",
    PASSWORD_RESET: "Password reset successfully.",
    SUBADMIN_CREATED_SUCCESSFULLY: "Sub-admin created successfully.",
    PASSWORD_LINK_SENT: "Password link sent successfully.",
    ADDRESS_UPDATED_SUCCESSFULLY: "Address updated successfully.",
    ADDRESS_REQUIRED: "Address is required.",
    DELETED_SUCCESSFULLY: "Deleted successfully.",
    UPDATED_SUCCESSFULLY: "Updated successfully.",
    DUPLICATE_DATE: "Slot for this date already exists.",
    SOMETHING_WENT_WRONG: "Something went wrong.",
    DISCOUNT_AMOUNT_CANNOT_BE_MORE_THAN_100: "Discount amount cannot be more than 100%.",
    BANNER_ALREADY_EXISTS: "Banner already exists.",
    ACCESS_DENIED: "Access Denied.",
    ENTER_VALID_CODE: "Please enter a valid referral code.",
    COUPON_ALREADY_EXISTS: "Coupon already exists.",
    GIFT_CARD_ALREADY_EXISTS: "Gift Card already exists.",
    PRODUCT_ALREADY_EXISTS: "Product already exists.",
    USER_NOT_VERIFIED: "User not verified.",
    LANDING_PAGE_ALREADY_EXISTS: "Landing page already exists.",
    ITEM_ALREADY_EXISTS: "Item already exists.",
    GEOFENCE_EXISTS_IN_CATEGORY: "This geofence exists in category.",
    USER_CREATED_SUCCESSFULLY: "User created successfully. ",
    BANK_COORDINATER_CREATED_SUCCESSFULLY: "Coordinater created successfully. ",
    DRIVER_UPDATED_SUCCESSFULLY: "Driver updated successfully. ",
    DO_NOT_SERVE_THIS_LOCATION: "We do not serve at this location please try again later!",
    INVAILD_URL: "Invalid Url",
    GOOD_URL: "Good Url",
    ORDER_NOT_FOUND: "Order not found",
    VERIFICATION_CODE_SENT_ON_PHONE: "Verification code sent on phone.",
    EMAIL_UPDATE_SUCCESSFULLY: "Email update successfully.",
    PHONE_UPDATE_SUCCESSFULLY: "Phone update successfully.",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED ACCESS",
    SUBADMIN_ROLE_EXISTS: "SubAdminRole already exists",
    SUBADMIN_NOT_FOUND: "SUBADMIN_NOT_FOUND",
    BANK_EXISTS: "Bank already exists.",
    BANK_NOT_FOUND: "Bank not found .",
    CASE_NOT_FOUND: "Case not found.",
    BANK_UPDATED: "Bank Updated successfully",
    INVALID_FAQ: "Invalid faq.",
    DATA_NOT_FOUND: "Data not found.",
    DATA_UPDATED: "Data updated successfully.",
    DATA_ADDED: "Data added successfully.",
    LOAN_ONGOING_REQUEST: "There is a ongoing loan request .",
    CONTACT_MISSING: "User contact missing",
    LOAN_UPDATED: "Loan details updated successfully",
    SUBADMINS_LISTED_SUCCESSFULLY: "Subsadmins listed successfully.",
    SUBADMIN_LISTED_SUCCESSFULLY: "Subsadmin fetched successfully.",
    CATEGORY_CREATED_SUCCESSFULLY: "Category created successfully",
    CATEGORY_NOT_FOUND: "Category not found",
    CATEGORY_EXISTS: "Category exists already",
    CATEGORIES_LISTED_SUCCESSFULLY: "Categories listed successfully",
    CATEGORY_FETCHED: "Category fetched successfully",
    CATEGORY_DELETED: "Category deleted successfully",
    CMS_DATA_FETCHED: "CMS data fetched",
    FAQ_DELETED: "FAQ deleted",
    INCORRECT_PASSWORD: "Incorrect password",
    DOCUMENT_APPROVAL_PENDING: "Documents are not approved by admin",
    NO_DATA_TO_EXPORT: "No data available to export",
    ACCESS_DENIED: "Access Denied.",

    INVALID_ID: "Invalid id",
    USER_ALREADY_REGISTERED: "User already registered",
    INVALID_FILE : "Invalid file",

    QR_CODE_GENERATED : "Qr code generated successfully",
    OFFER_EXPIRED : "Offer expired",
    OFFER_NOT_FOUND : "Offer not found",
    INVALID_DAY : "Invalid day",
    QR_CODE_SCANNED : "Qr code scanned successfully",
    INVALID_BUSINESS : "This qr code is not for this business.",
    SCAN_PREVIOUS_QR_FIRST : "You must scan previous qr first before scanning this qr.",
    SCAN_QR_BEFORE_GENERATING_NEXT_QR : "Scan qr before generating next qr",
    QR_ALREADY_SCANNED : "This qr code has already been scanned.",
    INVALID_SCAN_DATE : "Invalid scan date",
    QR_NOT_FOUND : "Qr not found",
    BANNER_LIMIT_EXCEED: "You can add only 7 banner at a time.",

    ACTIVE_SUBSCRIPTIONS_FOUND: "Product cannot be deleted because it has active subscriptions.",
    CREATED_COMMUNITY_FORUM : "Created a community forum",
    CREATED_POST : "Created a post",
    SUBJECT_OTP : "OTP Verification",
    SUBJECT_WELCOME : "Welcome to TkFit",

    BUSINESS_NOT_FOUND : "Business not found",
    SERVICE_NOT_FOUND : "Service not found",
    INVALID_INPUT : "Invalid input",
    NO_DATA_FOUND : "No data found",
    INVALID_OFFER : "Invalid offer",
    UNAUTHORIZED_PERSON : "Unauthorized person",
    INVALID_BUSINESS : "Invalid business",
    INVALID_SERVICE : "Invalid service",
    
    LIVE_SESSION_STARTED : "Live session started",
    LIVE_SESSION_ENDED : "Live session ended",
    THIS_SESSION_DOES_NOT_EXIST_OR_IS_NOT_ONGOING : "This session does not exist or is not ongoing.",
    LIVE_SESSION_CANNOT_START : "Live session cannot start",
    SLOT_FULL : "Slot of this live session is full",
    SLOT_BOOKED_SUCCESSFULLY : "Slot booked successfully",
    LIVE_SESSION_CAN_START_BETWEEN_START_END_TIME : "Live session can start between start and end time",

    COMMENT_SENT_SUCCESSFULLY : "Comment sent successfully",
    USER_INVITED_SUCCESSFULLY : "User invited successfully.",
    INVALID_SESSION_ID : "Invalid session id.",
    LIKED_SUCCESSFULLY : "Liked successfully",
    UNLIKED_SUCCESSFULLY : "Unliked successfully",

    COMMENTED_ON_POST : "Commented on your post",
    COMMENTED_SUCCESSFULLY : "Commented successfully",
  }